language: node_js
node_js: stable
branches:
  only:
  - docs

install:
  - npm install

script:
  - hexo cl
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "chasiny"
  - git config user.email "466071353@qq.com"
  - git add .
  - git commit -m "update"
  - git push --quiet --force https://$REPO_TOKEN@github.com/chasiny/chasiny.github.io.git master